export const quizTitleMap = {
  AI: 'Artificial Intelligence',
  PM: 'Project Management',
  SE: 'Software Engineering',
  Canva: 'Canva',
  React: 'React',
  Flutter: 'Flutter',
  EH: 'Ethical Hacking',
  CS: 'Communication Skills',
  Photoshop: 'Photoshop',
  RN: 'React Native',
  DA: 'Data Analysis',
  UIUX: 'UI/UX Design',
  Python: 'Python',
  DM: 'Digital Marketing',
};
